### PR TITLE
Fixed boolean encoding in the web interface.

### LINKED ISSUE #43: Web browsable API does not encode booleans correctly
Sending a boolean as an argument to a route gets encoded as a dictionary -- if you set `validate=True`, you'll always get the response '"message": "InvalidParamsError: <type 'dict'> is not the correct type <type 'bool'> for ...', if you do not set `validate=True`, then every argument is considered "truthy".  

The API works correctly when using curl directly.

The problem can be created by running the app below (Flask 0.10.1, Flask-JSONRPC 0.3), and navigating to http://localhost:5000/api/browse/#/say
```
from flask import Flask                                         
from flask_jsonrpc import JSONRPC                               
                                                                
app = Flask(__name__)                                           
jsonrpc = JSONRPC(app, '/api', enable_web_browsable_api=True)   
                                                                
                                                                
@jsonrpc.method('say(hi=bool) -> String', validate=True)        
def say(hi=False):                                              
    if hi:                                                      
        return "hi"                                             
    return "bye"                                                
                                                                
                                                                
@jsonrpc.method('nsay(n=int, hi=bool) -> String', validate=True)
def nsay(n=5, hi=False):                                        
    if hi:                                                      
        return n * "hi "                                        
    return n * "bye "                                           
                                                                
                                                                
if __name__ == '__main__':                                      
    app.run(host='0.0.0.0', debug=True)       
```

### PR DESCRIPTION
**Pull request by obi1kenobi**
This fixes #43.

Please let me know what I can do to help get this merged and released on PyPI ASAP -- it's currently blocking one of my projects.

### CODE REVIEW

**Comment by obi1kenobi** [comment]
Hey nycholas, thanks for merging this so promptly. Please let me know when you are able to release a new version to PyPI, I would love to be able to get my hands on this.

**Comment by nycholas** [comment]
Hi,

I need to resolve all open questions and then up to a version.

**Comment by nycholas** [comment]
Hi,

I can release minor version tomorrow.

Thank you.

**Comment by obi1kenobi** [comment]
Thank you, looking forward to it!

**Comment by nycholas** [comment]
@obi1kenobi 

https://pypi.python.org/pypi?name=Flask-JSONRPC&version=0.3.1&:action=display

Thank you.

**Comment by obi1kenobi** [comment]
Much appreciated, thank you for your prompt action!

**Pull request merged**
