### PR TITLE
Allow multiple JSONRPC sites with individual web UIs

### PR DESCRIPTION
**Pull request by obi1kenobi**
Ensures that multiple sites (with different prefixes) can be registered into the blueprint. This allows the JSONRPC sites to be entirely independent from each other -- site A can have separate endpoints and a separate web UI from site B, all of them accessible via the appropriate site's prefix (e.g. `/apiA` and `/apiB`)

### CODE REVIEW

**Comment by nycholas** [comment]
Hello,

Try this?

 https://github.com/cenobites/flask-jsonrpc/tree/master/examples/multiplesite

Thank you.

**Comment by obi1kenobi** [comment]
Hey, thanks for the reply. While that example works, the web UI contains the endpoints for both JSONRPC sites. My PR makes it so that each JSONRPC site has its own web UI, and each web UI only shows its own endpoints -- which is critical for my use case.

**Comment by eyurtsev** [comment]
+1

**Comment by nycholas** [comment]
Hi, 

On new release (1.0.0) was added this PR.

Examples:

https://github.com/cenobites/flask-jsonrpc/blob/release/v1.0.0/tests/contrib/test_browse.py#L85
https://github.com/cenobites/flask-jsonrpc/blob/release/v1.0.0/tests/contrib/test_browse.py#L188

Thank you.

**Pull request closed without merging**
